apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver # This is the label of the pod
  type: LoadBalancer # One of ClusterIP, NodePort, LoadBalancer, or ExternalName
  # type: NodePort # One of ClusterIP, NodePort, LoadBalancer, or ExternalName
  ports:
  - name: goserver-service
    port: 80 # Service port
    protocol: TCP
    targetPort: 8000 # Container port. Defaults to the same value as the port field if not defined
    # NodePort vs ClusterIP - NodePort exposes the service on each Node’s IP at a static port (the NodePort). A ClusterIP service is the default Kubernetes service. It gives you a stable IP and a single DNS name by which the service is accessible.
    # LoadBalancer generates an IP address for the service and forwards traffic to the service. It requires a cloud provider that supports the creation of external load balancers.
    # nodePort: 30001 # If not provided, Kubernetes will allocate a port from a range (default: 30000-32767)

    # Node 1: 30000 -> 32767 (NodePort range)
    # Independetly of the NodePort value, the service will be available on all nodes on the same port 